name: Build and Publish to NuGet

on:
  workflow_run:
    workflows: ["Build"]
    branches: [ release ]
    types:
      - completed

jobs:
  publish-nuget:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: src/Liberfy.UI
    - name: Build
      run: dotnet build src/Liberfy.UI/Liberfy.UI.sln --no-restore
    - name: Publish to NuGet
      uses: brandedoutcast/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: src/Liberfy.UI.Wpf/Liberfy.UI.Wpf.csproj
        VERSION_REGEX: '^\s*<PackageVersion>(.*)<\/PackageVersion>\s*$'
        TAG_FORMAT: '*'
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}